target 'iosApp' do
#   use_frameworks!
  platform :ios, '14.1'
  pod 'MultiPlatformLibrary', :path => '../MultiPlatformLibrary'
  pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.11.0'
end